### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by pps83** [yahoo/node-info#4]
default clean nodejs 6.6.0 install and this code:

```
var express = require('express');
var nodeinfo = require('node-info');
var app = express();
app.use(nodeinfo());
app.listen(8081);
```

produce this error:

> 
> TypeError: Cannot read property 'accepts' of undefined
>     at /work/http/node_modules/node-info/model/ni.js:86:29
>     at Array.forEach (native)
>     at NodeInfo.<anonymous> (/work/http/node_modules/node-info/model/ni.js:67:33)
>     at /work/http/node_modules/read-installed/read-installed.js:138:5
>     at /work/http/node_modules/read-installed/read-installed.js:251:14
>     at cb (/work/http/node_modules/slide/lib/async-map.js:47:24)
>     at /work/http/node_modules/read-installed/read-installed.js:251:14
>     at cb (/work/http/node_modules/slide/lib/async-map.js:47:24)
>     at /work/http/node_modules/read-installed/read-installed.js:251:14
>     at asyncMap (/work/http/node_modules/slide/lib/async-map.js:27:18)
>

Another point: can't you just add a real working sample code and not some random non-working piece? so that it would work without trying to figure out what's missing and what url to hit to get it working.
This isn't enough to get it running:
```
var nodeinfo = require('node-info');
app.use(nodeinfo());
```

**Comment by davglass** [comment]
My apologies, this module is well over 2 years old and has not been tested with newer modules. `read-installed` has changed a few times in the last couple of years :)

I'll try to look into this tomorrow when I have a chance.

**Comment by pps83** [comment]
After a bit of investigations here's the reason why it doesn't work: it assumes that there is package.json present and without it node-info generates exceptions, while IMO it should show only the top "Node environment information" table and say below that package.json is required to show more details.

**Comment by nobso** [comment]
@pps83 Thanks for letting us know.
First of all, there is a bug that i just fixed. Yes, you are right, by design it needs a package.json

**Comment by nobso** [comment]
>  can't you just add a real working sample code and not some random non-working piece?

@pps83  That's a real working sample and it works with v6.6.0. Your code would also work after this fix. In case, if you hadn't noticed, we have a detailed example https://github.com/yahoo/node-info/blob/master/example/node-info.js

**Comment by nobso** [comment]
@pps83 The fix is packaged. We will look into your suggestion of showing the "Node environment information". Thanks for helping us!
